services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: nvd_db
      POSTGRES_USER: nvd_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nvd_db
      SPRING_DATASOURCE_USERNAME: nvd_user
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
